[project]
name = "jx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "equinox>=0.12.2",
    "jax[tpu]>=0.7",
    "jaxtyping>=0.3.2",
    "transformers>=4.54.0",
]
